version = 0.1

[default.deploy.parameters]
stack_name = "riddhi-serverless-stack"
resolve_s3 = true
s3_prefix = "riddhi-serverless-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
